baseurl = "https://zhenkuo.com/"
title = "zhenkuo"
author = "Zhenkuo Liu"
canonifyurls = true
languagecode = "zh-CN"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "zhenkuo"
  disableWebFonts = false

[[menu.main]]
    name = "文章"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "关于"
    url  = "/about"
    weight = 2

[[menu.main]]
    name = "Github"
    url  = "https://github.com/bradliu"
    weight = 3